### ISSUE TITLE
Add install option for ROS noetic

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/rover_tools_ros1#11]
Currently melodic is the default ROS1 option but its become hard to install Ubuntu 20.04 on an RPi

**Comment by Lukas-W8less** [comment]
I second this, we're trying to use a Rover Zero in an existing ROS Noetic environment, and the install tools depend on ROS Melodic.

**Comment by Lukas-W8less** [comment]
To confirm, is this support provided by the noetic_test branch?
